
title:               'Ryan Grier'
tagline:             'Personal Website'
description: >- # this means to ignore newlines until "baseurl:"
  A site where I write (poorly) about a lot of dumb stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.ryangrier.com

# Build settings
# theme: minima
paginate: 5
paginate_path: /:num/
plugins:             
  - jekyll-paginate
  - jekyll-feed
  
permalink: pretty  
permalink: /:year/:month/:day/:title/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
